import { NextRequest, NextResponse } from 'next/server';
import { generateASCIIFloorPlan, prepareProjectContext } from '@/lib/ai/context';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { getProviderConfig } from '@/lib/ai/key-manager';

interface ImagenPrediction {
    bytesBase64Encoded: string;
    mimeType: string;
}

export async function POST(req: NextRequest) {
    try {
        const body = await req.json();
        const { input, project } = body;

        if (!input) {
            return NextResponse.json({ error: 'Input is required' }, { status: 400 });
        }

        const providerConfig = getProviderConfig('gemini');
        const apiKey = providerConfig.apiKey;
        const modelName = providerConfig.model; // This is gemini-3-flash-preview or whatever is configured

        if (!apiKey) {
            throw new Error("API_KEY is missing or invalid");
        }

        let systemInstruction = `You are a world-class architectural visualizer and Master Planner.
Your task is to generate EXACTLY 4 highly detailed pre-visualization images for an architectural project.
- Provide 4 distinct variations (e.g., modern, rustic, classical, minimalist) or 4 slightly varied angles/lighting setups if the user is very specific.
- You MUST ACTUALLY GENERATE the images. Output the 4 images natively in your response parts.`;

        if (project && Object.keys(project.nodes).length > 1) {
            const asciiPlan = generateASCIIFloorPlan(project);
            systemInstruction += `\n\nCRITICAL: The user already has a structure. You MUST generate images that visually incorporate or build upon this existing layout:
\`\`\`
${asciiPlan}
\`\`\`
Ensure the images look like modifications or refinements of their current house.`;
        }

        const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;
        
        const reqBody = {
            contents: [
                {
                    role: 'user',
                    parts: [{ text: `User request: "${input}"\n\nPlease output the 4 architectural render images now.` }]
                }
            ],
            system_instruction: { parts: [{ text: systemInstruction }] },
            generation_config: {
                temperature: 0.7
            }
        };

        const response = await fetch(url, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(reqBody)
        });

        if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`Gemini API Error ${response.status}: ${errorText}`);
        }

        const data = await response.json();
        const images: string[] = [];

        if (data.candidates && data.candidates.length > 0) {
            const parts = data.candidates[0].content?.parts || [];
            for (const part of parts) {
                if (part.inlineData && part.inlineData.mimeType?.startsWith('image/') && part.inlineData.data) {
                    images.push(part.inlineData.data);
                } else if (part.executableCode) {
                    // skip
                }
            }
        }

        if (images.length === 0) {
            return NextResponse.json({ error: "No images were generated by the model. It might have output text instead.", images: [] }, { status: 500 });
        }

        return NextResponse.json({ images: images.slice(0, 4) });

    } catch (error: any) {
        console.error('Plan generation error:', error);
        return NextResponse.json(
            { error: error.message || 'Internal server error' },
            { status: 500 }
        );
    }
}
